global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
- job_name: 'ping-agent'
  metrics_path: /metrics
  static_configs:
  - targets: [ 'ping-agent:8000' ]

- job_name: 'http-agent'
  metrics_path: /metrics
  static_configs:
  - targets: [ 'http-agent:8001' ]

- job_name: 'prometheus'
  static_configs:
  - targets: [ 'localhost:9090' ]
